#title: Just the Docs Template
  #description: A starter template for a Jeykll site using the Just the Docs theme!
  #theme: just-the-docs

  #url: https://just-the-docs.github.io

  #aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template

title: Resources
logo: "/assets/images/logo.png"
  #description: >- # this means to ignore newlines until "baseurl:"
  #  Hi. Welcome to the IIIT Programming Club! 
  #  We are just a bunch of people who love to code and participate in programming contests! 
  #  Programming can be fun, and we are here to prove exactly that. 
#remote_theme: pmarsceill/just-the-docs
# domain: iiit-programming-club.github.io
# baseurl: "/iiit-programming-club" # the subpath of your site, e.g. /blog
# url: "https://iiit-programming-club.github.io" # the base hostname & protocol for your site, e.g. http://example.com
aux_links:
  "Github":
    - "https://github.com/HPC-Heterogeneous-Graph-Algorithms"
plugins:
  # Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: pmarsceill/just-the-docs
